name: CommandWatcher

version: ${project.version}

description: Listen to Commands

author: McLuke300

main: me.mcluke300.commandlistener.CommandListener



commands:
   CW:
      description: Enables CommandWatch
      permission: commandwatch.watch
